
trigger:
- master

pool:
  vmImmage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
    - job: 'BuildAndpublish'
      displayName: 'Build and Publish'
      steps:
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'GitHub Container Registry'
            dockerComposeFile: '**/docker-compose.yml'
            additionalDockerComposeFiles: 'build.docker-compose.yml'
            action: 'Build services'
            additionalImageTags: '$(Build.BuildNumber)'
        - task: DockerCompose@0
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'GitHub Container Registry'
            dockerComposeFile: '**/docker-compose.yml'
            additionalDockerComposeFiles: 'build.docker-compose.yml'
            action: 'Push services'
            additionalImageTags: '$(Build.BuildNumber)'

  - stage: DeployProd
    dependsOn: build
    jobs:
    - deployment: infrastructure
      environment: production
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: Docker@2
                inputs:
                  containerRegistry: 'GitHub Container Registry'
                  command: 'login'
              - task: AzureCLI@2
                inputs:
                  azureSubscription: 'Fabrikam-Azure'
                  scriptType: 'bash'
                  scriptLocation: 'scriptPath'
                  scriptPath: './infrastructure/ado-pipelines.deploy-infrastructure.sh'
                env:
                  CR_PAT: $(CR_PAT)
